export const ACTIONS = {
  QUERY_FORM_STATE_CHANGE: 'QUERY_FORM_STATE_CHANGE',
  REFRESH_QUERIES: 'REFRESH_QUERIES',
  RESET_QUERY_DIALOG: 'RESET_QUERY_DIALOG',
  RESET_QUERY_DIALOG_CODE: 'RESET_QUERY_DIALOG_CODE',
  SUBMITTING_DONE: 'SUBMITTING_DONE',
  SUBMITTING_NEW_QUERY: 'SUBMITTING_NEW_QUERY',
  UPDATE_CODE: 'UPDATE_CODE',
};
